# Runs on all other branches and ensures that the code builds successfully
name: Build

on:
  push:
    branches:
      - "*"

jobs:
  build-switcher:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up Node.js
        uses: actions/setup-node@v1
        with:
          node-version: lts/*
      - name: Install dependencies
        run: npm install
      - name: Build
        run: npm run switcher:build
