# Runs on all other branches and ensures that the code builds successfully
name: Build

on:
  push:
    branches-ignore:
      - master

jobs:
  build-switcher:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up Node.js
        uses: actions/setup-node@v1
        with:
          node-version: "22.x"
      - name: Install Switcher dependencies
        run: npm ci
      - name: Install Host dependencies
        run: npm ci
        working-directory: ./host
      - name: Build
        run: npm run switcher:build
