# Runs on all other branches and ensures that the code builds successfully
name: Build

on:
  push:
    branches-ignore:
      - master

jobs:
  build-switcher:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up Node.js
        uses: actions/setup-node@v1
        with:
          node-version: "22.x"
      - name: Install dependencies
        run: 
          npm install && npm -w host install
      - name: Build Switcher
        run: npm run switcher:build
      - name: Package Switcher
        run: npm run switcher:package:latest-linux-x64
      - name: Build Host
        run: npm run host:build
